name: Deploy to Render on merge to main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Render
        run: |
          npm run build
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }} 

          
